/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CreateRouteImport } from './routes/create'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MarketIdRouteImport } from './routes/market.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketIdRoute = MarketIdRouteImport.update({
  id: '/market/$id',
  path: '/market/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/leaderboard': typeof LeaderboardRoute
  '/portfolio': typeof PortfolioRoute
  '/market/$id': typeof MarketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/leaderboard': typeof LeaderboardRoute
  '/portfolio': typeof PortfolioRoute
  '/market/$id': typeof MarketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/leaderboard': typeof LeaderboardRoute
  '/portfolio': typeof PortfolioRoute
  '/market/$id': typeof MarketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/create' | '/leaderboard' | '/portfolio' | '/market/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/create' | '/leaderboard' | '/portfolio' | '/market/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/create'
    | '/leaderboard'
    | '/portfolio'
    | '/market/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CreateRoute: typeof CreateRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PortfolioRoute: typeof PortfolioRoute
  MarketIdRoute: typeof MarketIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/$id': {
      id: '/market/$id'
      path: '/market/$id'
      fullPath: '/market/$id'
      preLoaderRoute: typeof MarketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CreateRoute: CreateRoute,
  LeaderboardRoute: LeaderboardRoute,
  PortfolioRoute: PortfolioRoute,
  MarketIdRoute: MarketIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
